name: Build and Deploy Python App to Azure Web App - devops-pythonwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write  # ✅ Required for OIDC authentication
  contents: read   # ✅ Required for checking out code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and Start Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (e.g., PyTest)

      - name: Zip Artifact for Deployment
        run: zip release.zip ./* -r

      - name: Upload Artifact for Deployment Jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip Artifact for Deployment
        run: unzip release.zip

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'devops-pythonwebapp'
          slot-name: 'Production'
